#!/usr/bin/env node
/**
 * Behavior tests for issue #87: verify-scrub flagged Luhn-valid 13-digit
 * Unix-millisecond timestamps as credit-card leaks. After the fix, those
 * timestamps should be silently skipped while genuine 13-digit card numbers
 * remain detected.
 *
 * Zero-dep: relies only on the Node assert module. Exits non-zero on first
 * failure so it can be wired into a Pester wrapper.
 */

'use strict';

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const SCRIPTS_DIR = __dirname;
const VERIFY = path.join(SCRIPTS_DIR, 'verify-scrub.js');

function tmpHarWith(value) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-ts-test-'));
    const har = {
        log: {
            version: '1.2',
            creator: { name: 'cc-ts-test', version: '1' },
            entries: [{
                request: { method: 'GET', url: 'https://x.invalid/', headers: [] },
                response: {
                    status: 200,
                    statusText: 'OK',
                    headers: [{ name: 'content-type', value: 'application/json' }],
                    content: { mimeType: 'application/json', text: JSON.stringify({ v: value }) }
                }
            }]
        }
    };
    const harPath = path.join(dir, 'sample.har');
    fs.writeFileSync(harPath, JSON.stringify(har));
    return harPath;
}

function runVerify(harPath) {
    try {
        execFileSync('node', [VERIFY, '--in', harPath], { stdio: 'pipe' });
        return { code: 0, stdout: '', stderr: '' };
    } catch (e) {
        return {
            code: e.status,
            stdout: (e.stdout || '').toString(),
            stderr: (e.stderr || '').toString()
        };
    }
}

// Visa-format 13-digit number that is Luhn-valid: 4111111111111 has been
// generated by hand below. Let's confirm a known good test card first.
// 4222222222222 -> luhn check: digits from right doubling every second...
// Easier: use 4111111111111 (a classic Visa test pattern is 4111111111111**4**
// for 16 digits; for 13 digits we need a verified Luhn-valid number).
// Use 4242424242424 -- verify Luhn:
//   digits R-to-L: 4 2 4 2 4 2 4 2 4 2 4 2 4
//   double every-second-from-right: 4 4 4 4 4 4 4 4 4 4 4 4 4  (each 2*2=4)
//   sum = 13*4 = 52 -> not 0 mod 10. Not Luhn.
// Just compute one programmatically.
function luhn(s) {
    let sum = 0, alt = false;
    for (let i = s.length - 1; i >= 0; i--) {
        let d = +s[i];
        if (alt) { d *= 2; if (d > 9) d -= 9; }
        sum += d; alt = !alt;
    }
    return sum % 10 === 0;
}

// Find a 13-digit Visa-prefix number (starts with 4) that is Luhn-valid
// AND is NOT in the recent-Unix-ms timestamp window. Using a deterministic
// generated value so the test is reproducible.
function findRealCard() {
    // Start from a value well below the 13-digit timestamp window
    // (timestamp window: ~1.26e12 -> ~2.53e12 for years 2010..2050).
    // 4000000000000 = 4e12 is INSIDE the window -- bad choice.
    // 4900000000000 = 4.9e12 -- OUTSIDE the window (> 2050) -- good.
    let base = 4900000000000n;
    for (let i = 0n; i < 1000n; i++) {
        const s = (base + i).toString();
        if (luhn(s)) return s;
    }
    throw new Error('no luhn-valid Visa-shape generated');
}

let passed = 0;

// ===================================================================
// Case 1: Unix-ms timestamp (luhn-valid by coincidence) is NOT a leak.
// ===================================================================
{
    const ts = '1777603192214'; // 2026-05-01, the value from the dogfood
    assert.ok(luhn(ts), 'precondition: ' + ts + ' should be luhn-valid');
    const har = tmpHarWith(ts);
    const r = runVerify(har);
    assert.strictEqual(
        r.code, 0,
        'expected exit 0 for a recent Unix-ms timestamp, got ' + r.code +
        '\nstderr: ' + r.stderr
    );
    passed++;
}

// ===================================================================
// Case 2: Genuine 13-digit Visa-shape credit card IS caught.
// ===================================================================
{
    const card = findRealCard();
    assert.ok(luhn(card), 'precondition: ' + card + ' is luhn-valid');
    // Ensure outside the timestamp window so the new heuristic does NOT
    // suppress it on the basis of "looks like a timestamp".
    const n = Number(card);
    assert.ok(
        n < 1.26e12 || n > 2.53e12,
        'precondition: card ' + card + ' must lie OUTSIDE recent-ms window'
    );
    const har = tmpHarWith(card);
    const r = runVerify(har);
    assert.strictEqual(
        r.code, 3,
        'expected exit 3 for a real 13-digit credit card, got ' + r.code +
        '\nstdout: ' + r.stdout + '\nstderr: ' + r.stderr
    );
    assert.match(r.stderr, /credit-card/, 'expected credit-card leak label');
    passed++;
}

// ===================================================================
// Case 3: A 16-digit Luhn-valid timestamp-like number is STILL flagged
// (16-digit window for years 2010-2050 doesn't exist in Unix-ms; this
//  asserts the heuristic only narrows credit-card detection at the
//  exact 13-digit length, not generically).
// ===================================================================
{
    // 4111111111111111 = canonical Visa test card, 16 digits, luhn-valid.
    const card16 = '4111111111111111';
    assert.ok(luhn(card16));
    const har = tmpHarWith(card16);
    const r = runVerify(har);
    assert.strictEqual(
        r.code, 3,
        'expected exit 3 for canonical 16-digit Visa test card, got ' + r.code
    );
    assert.match(r.stderr, /credit-card/, 'expected credit-card label');
    passed++;
}

console.log('All verify-scrub-cc-timestamp tests passed (' + passed + '/3).');
