#!/usr/bin/env node
/**
 * Behavior tests for issue #87: verify-scrub flagged Luhn-valid 13-digit
 * Unix-millisecond timestamps as credit-card leaks. Those timestamps must be
 * silently skipped while genuine 13-digit card numbers remain detected.
 *
 * The mechanism changed in issue #295 -- the explicit year-2010..2050
 * millisecond window is gone, and the behavior now falls out of the issuer
 * identifier check, because a Unix-ms timestamp begins `17` and no card
 * network has been assigned that prefix. These assertions are unchanged and
 * still guard the behavior; only the reason it holds is different.
 *
 * Zero-dep: relies only on the Node assert module. Exits non-zero on first
 * failure so it can be wired into a Pester wrapper.
 */

'use strict';

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const SCRIPTS_DIR = __dirname;
const VERIFY = path.join(SCRIPTS_DIR, 'verify-scrub.js');

function tmpHarWith(value) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-ts-test-'));
    const har = {
        log: {
            version: '1.2',
            creator: { name: 'cc-ts-test', version: '1' },
            entries: [{
                request: { method: 'GET', url: 'https://x.invalid/', headers: [] },
                response: {
                    status: 200,
                    statusText: 'OK',
                    headers: [{ name: 'content-type', value: 'application/json' }],
                    content: { mimeType: 'application/json', text: JSON.stringify({ v: value }) }
                }
            }]
        }
    };
    const harPath = path.join(dir, 'sample.har');
    fs.writeFileSync(harPath, JSON.stringify(har));
    return harPath;
}

function runVerify(harPath) {
    try {
        execFileSync('node', [VERIFY, '--in', harPath], { stdio: 'pipe' });
        return { code: 0, stdout: '', stderr: '' };
    } catch (e) {
        return {
            code: e.status,
            stdout: (e.stdout || '').toString(),
            stderr: (e.stderr || '').toString()
        };
    }
}

// Visa-format 13-digit number that is Luhn-valid: 4111111111111 has been
// generated by hand below. Let's confirm a known good test card first.
// 4222222222222 -> luhn check: digits from right doubling every second...
// Easier: use 4111111111111 (a classic Visa test pattern is 4111111111111**4**
// for 16 digits; for 13 digits we need a verified Luhn-valid number).
// Use 4242424242424 -- verify Luhn:
//   digits R-to-L: 4 2 4 2 4 2 4 2 4 2 4 2 4
//   double every-second-from-right: 4 4 4 4 4 4 4 4 4 4 4 4 4  (each 2*2=4)
//   sum = 13*4 = 52 -> not 0 mod 10. Not Luhn.
// Just compute one programmatically.
function luhn(s) {
    let sum = 0, alt = false;
    for (let i = s.length - 1; i >= 0; i--) {
        let d = +s[i];
        if (alt) { d *= 2; if (d > 9) d -= 9; }
        sum += d; alt = !alt;
    }
    return sum % 10 === 0;
}

// A deterministic 13-digit Luhn-valid run carrying the Visa issuer
// identifier (leading `4`), which Visa does mint at 13 digits. Generated
// rather than published, so the test is reproducible without committing a
// card number.
function findRealCard() {
    let base = 4900000000000n;
    for (let i = 0n; i < 1000n; i++) {
        const s = (base + i).toString();
        if (luhn(s)) return s;
    }
    throw new Error('no luhn-valid Visa-shape generated');
}

// Since issue #297 Stage 7, a card is IDENTITY-class shape evidence: it exits
// with the ADVISORY code, not the gating one. Non-zero either way -- it is the
// ARTIFACT that survives an advisory finding, not the exit code -- but the two
// codes mean different things to capture-har.js, so these assert the exact one.
// Loosening them to "non-zero" would let the change be quietly undone by making
// credit-card gate again, which is the one repair that must not pass here.
const EXIT_ADVISORY = 4;

let passed = 0;

// ===================================================================
// Case 1: Unix-ms timestamp (luhn-valid by coincidence) is NOT a leak.
// ===================================================================
{
    const ts = '1777603192214'; // 2026-05-01, the value from the dogfood
    assert.ok(luhn(ts), 'precondition: ' + ts + ' should be luhn-valid');
    const har = tmpHarWith(ts);
    const r = runVerify(har);
    assert.strictEqual(
        r.code, 0,
        'expected exit 0 for a recent Unix-ms timestamp, got ' + r.code +
        '\nstderr: ' + r.stderr
    );
    passed++;
}

// ===================================================================
// Case 2: Genuine 13-digit Visa-shape credit card IS caught.
// ===================================================================
{
    const card = findRealCard();
    assert.ok(luhn(card), 'precondition: ' + card + ' is luhn-valid');
    const har = tmpHarWith(card);
    const r = runVerify(har);
    assert.strictEqual(
        r.code, EXIT_ADVISORY,
        'expected the advisory exit for a real 13-digit credit card, got ' + r.code +
        '\nstdout: ' + r.stdout + '\nstderr: ' + r.stderr
    );
    assert.match(r.stderr, /credit-card/, 'expected credit-card leak label');
    passed++;
}

// ===================================================================
// Case 3: the gate still does its job. Skipping timestamps must not
// have been implemented as "skip 13-digit runs" -- the canonical Visa
// test card is 16 digits and must still be reported.
// ===================================================================
{
    // 4111111111111111 = canonical Visa test card, 16 digits, luhn-valid.
    const card16 = '4111111111111111';
    assert.ok(luhn(card16));
    const har = tmpHarWith(card16);
    const r = runVerify(har);
    assert.strictEqual(
        r.code, EXIT_ADVISORY,
        'expected the advisory exit for the canonical 16-digit Visa test card, got ' + r.code
    );
    assert.match(r.stderr, /credit-card/, 'expected credit-card label');
    passed++;
}

console.log('All verify-scrub-cc-timestamp tests passed (' + passed + '/3).');
